/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "roman_calculator_util-test.check" instead.
 */

#include <check.h>

#line 1 "roman_calculator_util-test.check"
#include "roman_calculator_util.h"

START_TEST(sortMDCLXI_to_MDCLXI)
{
#line 4
    ck_assert_str_eq(sort("MDCLXI"), "MDCLXI");

}
END_TEST

START_TEST(sortIXLCDM_to_MDCLXI)
{
#line 7
    ck_assert_str_eq(sort("IXLCDM"), "MDCLXI");

}
END_TEST

START_TEST(sortCCLL_to_CCLL)
{
#line 10
    ck_assert_str_eq(sort("CCLL"), "CCLL");

}
END_TEST

START_TEST(sortMIIX_to_MXII)
{
#line 13
    ck_assert_str_eq(sort("MIIX"), "MXII");

}
END_TEST

START_TEST(expandsIX_to_VIIII)
{
#line 16
    ck_assert_str_eq(expand("IX"), "VIIII");

}
END_TEST

START_TEST(expandsIV_to_IIII)
{
#line 19
    ck_assert_str_eq(expand("IV"), "IIII");

}
END_TEST

START_TEST(expandsXC_to_LXXXX)
{
#line 22
    ck_assert_str_eq(expand("XC"), "LXXXX");

}
END_TEST

START_TEST(expandsXL_to_XXXX)
{
#line 25
    ck_assert_str_eq(expand("XL"), "XXXX");

}
END_TEST

START_TEST(expandsCM_to_DCCCC)
{
#line 28
    ck_assert_str_eq(expand("CM"), "DCCCC");

}
END_TEST

START_TEST(expandsCD_to_CCCC)
{
#line 31
    ck_assert_str_eq(expand("CD"), "CCCC");



}
END_TEST

START_TEST(groupsVV_to_X)
{
#line 36
    ck_assert_str_eq(group("VV"), "X");

}
END_TEST

START_TEST(groupsXXXXX_to_L)
{
#line 39
    ck_assert_str_eq(group("XXXXX"), "L");

}
END_TEST

START_TEST(groupsLL_to_C)
{
#line 42
    ck_assert_str_eq(group("LL"), "C");

}
END_TEST

START_TEST(groupsCCCCC_to_D)
{
#line 45
    ck_assert_str_eq(group("CCCCC"), "D");

}
END_TEST

START_TEST(groupsDD_to_M)
{
#line 48
    ck_assert_str_eq(group("DD"), "M");

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, sortMDCLXI_to_MDCLXI);
    tcase_add_test(tc1_1, sortIXLCDM_to_MDCLXI);
    tcase_add_test(tc1_1, sortCCLL_to_CCLL);
    tcase_add_test(tc1_1, sortMIIX_to_MXII);
    tcase_add_test(tc1_1, expandsIX_to_VIIII);
    tcase_add_test(tc1_1, expandsIV_to_IIII);
    tcase_add_test(tc1_1, expandsXC_to_LXXXX);
    tcase_add_test(tc1_1, expandsXL_to_XXXX);
    tcase_add_test(tc1_1, expandsCM_to_DCCCC);
    tcase_add_test(tc1_1, expandsCD_to_CCCC);
    tcase_add_test(tc1_1, groupsVV_to_X);
    tcase_add_test(tc1_1, groupsXXXXX_to_L);
    tcase_add_test(tc1_1, groupsLL_to_C);
    tcase_add_test(tc1_1, groupsCCCCC_to_D);
    tcase_add_test(tc1_1, groupsDD_to_M);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
