/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "roman_calculator_util-test.check" instead.
 */

#include <check.h>

#line 1 "roman_calculator_util-test.check"
#include "roman_calculator_util.h"

START_TEST(sortMDCLXI_to_MDCLXI)
{
#line 4
    ck_assert_str_eq(sort("MDCLXI"), "MDCLXI");

}
END_TEST

START_TEST(sortIXLCDM_to_MDCLXI)
{
#line 7
    ck_assert_str_eq(sort("IXLCDM"), "MDCLXI");

}
END_TEST

START_TEST(sortCCLL_to_CCLL)
{
#line 10
    ck_assert_str_eq(sort("CCLL"), "CCLL");

}
END_TEST

START_TEST(sortMIIX_to_MXII)
{
#line 13
    ck_assert_str_eq(sort("MIIX"), "MXII");




}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, sortMDCLXI_to_MDCLXI);
    tcase_add_test(tc1_1, sortIXLCDM_to_MDCLXI);
    tcase_add_test(tc1_1, sortCCLL_to_CCLL);
    tcase_add_test(tc1_1, sortMIIX_to_MXII);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
